// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11LMV13x6Uh87RuYY-B2sKEeomidpW3g',
    appId: '1:476414345581:web:74975fcad8928635f39a64',
    messagingSenderId: '476414345581',
    projectId: 'flutter-5cdbb',
    authDomain: 'flutter-5cdbb.firebaseapp.com',
    storageBucket: 'flutter-5cdbb.firebasestorage.app',
    measurementId: 'G-HBZMVBS2WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBALGFeRq23SfEMGyN8iXsKNdcRPXostN8',
    appId: '1:476414345581:android:e8b29fec51d073e5f39a64',
    messagingSenderId: '476414345581',
    projectId: 'flutter-5cdbb',
    storageBucket: 'flutter-5cdbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGF67nJlKdaLeRY_lEofefJD3xicazec',
    appId: '1:476414345581:ios:360d32bf2aa093e1f39a64',
    messagingSenderId: '476414345581',
    projectId: 'flutter-5cdbb',
    storageBucket: 'flutter-5cdbb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGF67nJlKdaLeRY_lEofefJD3xicazec',
    appId: '1:476414345581:ios:360d32bf2aa093e1f39a64',
    messagingSenderId: '476414345581',
    projectId: 'flutter-5cdbb',
    storageBucket: 'flutter-5cdbb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11LMV13x6Uh87RuYY-B2sKEeomidpW3g',
    appId: '1:476414345581:web:ca6e9224887b7407f39a64',
    messagingSenderId: '476414345581',
    projectId: 'flutter-5cdbb',
    authDomain: 'flutter-5cdbb.firebaseapp.com',
    storageBucket: 'flutter-5cdbb.firebasestorage.app',
    measurementId: 'G-VRHQZSETJZ',
  );
}
